export const AgentsData = [
  {
    id:'41S',
    user:'Gil Dvir',
    role:'Agent',
    phone:'509841953',
    additional:'',
    status:'Active',
    customers:230,
    city:'Modein',
    trends:3,
  },
  {
    id:'S12',
    user:'Yafa Rozen',
    role:'Agent',
    phone:'558743977',
    additional:'',
    status:'Active',
    customers:118,
    city:'Rishon LeTsiyon',
    trends:1.9,
  },
  {
    id:'1D1',
    user:'Meni Porat',
    role:'CFO',
    phone:'559682702',
    additional:'Read Only',
    status:'Active',
    customers:23,
    city:'Tel-Aviv',
    trends:-3,
  },
  {
    id:'F1S7',
    user:'Nissim Gal',
    role:'Admin',
    phone:'528840937',
    additional:'',
    status:'Empty',
    customers:274,
    city:'Haifa',
    trends:2.6,
  },

]
